trigger:
  batch: true
  branches:
    include:
    - refs/tags/*

stages:
- stage: Deploy

  jobs:
  - deployment: Deploy
    environment: 'Azure DevOps Cleaner' # requires approvals to ensure updates are manully approved
    pool:
      vmImage: 'ubuntu-latest'

    variables:
      targetTag: $[replace(variables['Build.SourceBranch'], 'refs/tags/', '')]

      strategy:
        runOnce:
          deploy:
            steps:

            - task: DownloadGitHubRelease@0
              inputs:
                connection: '$(githubConnection)'
                userRepository: 'tinglesoftware/azure-devops-cleaner'
                defaultVersionType: 'specificTag'
                version: '$(targetTag)'

            - task: AzureCLI@2
              displayName: "Deploy to Container Apps"
              inputs:
                azureSubscription: $(azureConnection)
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: >
                  az deployment group create
                  --resource-group '$(azureResourceGroupName)'
                  --name 'azdo-cleaner-$(targetTag)'
                  --template-file $(System.ArtifactsDirectory)/main.bicep
                  --parameters "notificationsPassword=$(AzureDevOpsNotificationsPassword)"
                  --parameters "azureDevOpsProjectUrl=$(AzureDevOpsProjectUrl)"
                  --parameters "azureDevOpsProjectToken=$(AzureDevOpsToken)"
