name: Cleanup

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 */14 * *' # every 14 days

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Delete old packages (docker)
      uses: actions/delete-package-versions@v5
      with:
        package-name: 'azure-resources-cleaner'
        package-type: 'container'
        min-versions-to-keep: 20

    - name: Delete old packages (nuget)
      uses: actions/delete-package-versions@v5
      with:
        package-name: 'azure-resources-cleaner'
        package-type: 'nuget'
        min-versions-to-keep: 10
